In [1]:
import numpy as np

In [2]:
zeros_vector=np.zeros(50)
zeros_vector

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [3]:
type(zeros_vector)

numpy.ndarray

In [4]:
zero_matrix=np.zeros((3,13))
zero_matrix

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [5]:
non_zeros=np.ones((2,2))
non_zeros

array([[ 1.,  1.],
       [ 1.,  1.]])

In [6]:
array1=np.array([[1,6],[3,4]])
array1

array([[1, 6],
       [3, 4]])

In [7]:
type(array1)
array1.transpose()

array([[1, 3],
       [6, 4]])

In [8]:
array1[0:1]

array([[1, 6]])

In [9]:
array2=np.array([[4,6],[55,4]])
array2

array([[ 4,  6],
       [55,  4]])

In [10]:
sum=array1**array2
sum

array([[                   1,                46656],
       [-5935728490411247669,                  256]])

In [11]:
z1=np.array([1,2,4,5,7])
z1

array([1, 2, 4, 5, 7])

In [12]:
z2=z1+11
z2

array([12, 13, 15, 16, 18])

In [13]:
import numpy as np
i_n=np.array([12,32])

In [14]:
aa=i_n
aa

array([12, 32])

In [15]:
z1=[i_n]
z1


[array([12, 32])]

In [16]:
array1==array2 #done till here on 18june dsp 

array([[False,  True],
       [False,  True]], dtype=bool)

In [17]:
array1>array2

array([[False, False],
       [False, False]], dtype=bool)

In [18]:
las=np.linspace(0,100,13)
las

array([   0.        ,    8.33333333,   16.66666667,   25.        ,
         33.33333333,   41.66666667,   50.        ,   58.33333333,
         66.66666667,   75.        ,   83.33333333,   91.66666667,  100.        ])

In [19]:
las.shape


(13,)

In [20]:
array1.shape

(2, 2)

In [21]:
ran=np.random.print_function
ran

_Feature((2, 6, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 65536)

In [61]:

ran.size

12

In [24]:
M=np.array([[1,2],[3,4]],dtype=complex)
M

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [25]:
z=np.arange(0, 10, 1)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
z=np.arange(0, 100, 5)
z

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [26]:
z=np.arange(0, 100, 44)
z


array([ 0, 44, 88])

In [27]:
z=np.arange(-1,1,0.1)
z

array([ -1.00000000e+00,  -9.00000000e-01,  -8.00000000e-01,
        -7.00000000e-01,  -6.00000000e-01,  -5.00000000e-01,
        -4.00000000e-01,  -3.00000000e-01,  -2.00000000e-01,
        -1.00000000e-01,  -2.22044605e-16,   1.00000000e-01,
         2.00000000e-01,   3.00000000e-01,   4.00000000e-01,
         5.00000000e-01,   6.00000000e-01,   7.00000000e-01,
         8.00000000e-01,   9.00000000e-01])

In [28]:
corrdinate_mesh=np.mgrid[0:5,0:5]
corrdinate_mesh

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [37]:
aa=np.random.rand(3,3)
aa

array([[ 0.58641919,  0.12758334,  0.30747154],
       [ 0.82781686,  0.65030372,  0.73708004],
       [ 0.3112234 ,  0.15517287,  0.54268879]])

In [29]:
aa=np.random.rand(5,5)
aa


array([[ 0.73680007,  0.4027315 ,  0.53255993,  0.83535379,  0.39429983],
       [ 0.66725312,  0.92506911,  0.2428422 ,  0.5406626 ,  0.27854308],
       [ 0.09547272,  0.25830796,  0.62837717,  0.86113483,  0.84255331],
       [ 0.39304656,  0.78505936,  0.13828286,  0.22481456,  0.24665517],
       [ 0.96141947,  0.1557701 ,  0.71491232,  0.12382933,  0.1090531 ]])

In [40]:
diamat=np.diag([1,2,3,4,7,9])
diamat

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 9]])

In [31]:
diamat2=np.diag([1,2,3], k=1)
diamat2

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [32]:
#generating numby data object using real file.
data=np.genfromtxt('jokes.txt')
data

ValueError: Some errors were detected !
    Line #2 (got 3 columns instead of 11)
    Line #5 (got 10 columns instead of 11)
    Line #8 (got 16 columns instead of 11)
    Line #9 (got 1 columns instead of 11)
    Line #10 (got 2 columns instead of 11)
    Line #12 (got 9 columns instead of 11)
    Line #13 (got 4 columns instead of 11)
    Line #16 (got 4 columns instead of 11)
    Line #18 (got 7 columns instead of 11)
    Line #19 (got 7 columns instead of 11)
    Line #21 (got 15 columns instead of 11)
    Line #22 (got 7 columns instead of 11)
    Line #24 (got 7 columns instead of 11)
    Line #25 (got 4 columns instead of 11)
    Line #27 (got 7 columns instead of 11)
    Line #28 (got 3 columns instead of 11)
    Line #30 (got 14 columns instead of 11)
    Line #31 (got 7 columns instead of 11)
    Line #33 (got 9 columns instead of 11)
    Line #34 (got 3 columns instead of 11)
    Line #36 (got 8 columns instead of 11)
    Line #37 (got 3 columns instead of 11)
    Line #39 (got 9 columns instead of 11)
    Line #40 (got 7 columns instead of 11)
    Line #42 (got 6 columns instead of 11)
    Line #43 (got 9 columns instead of 11)
    Line #45 (got 8 columns instead of 11)
    Line #46 (got 7 columns instead of 11)
    Line #48 (got 10 columns instead of 11)
    Line #49 (got 10 columns instead of 11)
    Line #51 (got 13 columns instead of 11)
    Line #52 (got 6 columns instead of 11)
    Line #54 (got 8 columns instead of 11)
    Line #55 (got 7 columns instead of 11)
    Line #57 (got 12 columns instead of 11)
    Line #58 (got 7 columns instead of 11)
    Line #60 (got 8 columns instead of 11)
    Line #61 (got 6 columns instead of 11)
    Line #63 (got 9 columns instead of 11)
    Line #64 (got 2 columns instead of 11)
    Line #66 (got 12 columns instead of 11)
    Line #67 (got 5 columns instead of 11)
    Line #69 (got 10 columns instead of 11)
    Line #70 (got 5 columns instead of 11)
    Line #72 (got 8 columns instead of 11)
    Line #73 (got 14 columns instead of 11)
    Line #75 (got 6 columns instead of 11)
    Line #76 (got 10 columns instead of 11)
    Line #78 (got 10 columns instead of 11)
    Line #79 (got 4 columns instead of 11)
    Line #82 (got 8 columns instead of 11)
    Line #84 (got 8 columns instead of 11)
    Line #85 (got 6 columns instead of 11)
    Line #87 (got 9 columns instead of 11)
    Line #88 (got 6 columns instead of 11)
    Line #90 (got 14 columns instead of 11)
    Line #91 (got 1 columns instead of 11)
    Line #92 (got 8 columns instead of 11)
    Line #94 (got 12 columns instead of 11)
    Line #95 (got 7 columns instead of 11)
    Line #97 (got 12 columns instead of 11)
    Line #98 (got 4 columns instead of 11)
    Line #100 (got 13 columns instead of 11)
    Line #103 (got 14 columns instead of 11)
    Line #104 (got 2 columns instead of 11)
    Line #106 (got 9 columns instead of 11)
    Line #107 (got 6 columns instead of 11)
    Line #109 (got 9 columns instead of 11)
    Line #110 (got 4 columns instead of 11)
    Line #112 (got 14 columns instead of 11)
    Line #113 (got 4 columns instead of 11)
    Line #115 (got 8 columns instead of 11)
    Line #116 (got 3 columns instead of 11)
    Line #119 (got 6 columns instead of 11)
    Line #121 (got 10 columns instead of 11)
    Line #122 (got 7 columns instead of 11)
    Line #124 (got 5 columns instead of 11)
    Line #125 (got 5 columns instead of 11)
    Line #127 (got 10 columns instead of 11)
    Line #128 (got 7 columns instead of 11)
    Line #130 (got 7 columns instead of 11)
    Line #131 (got 3 columns instead of 11)
    Line #133 (got 9 columns instead of 11)
    Line #134 (got 4 columns instead of 11)
    Line #137 (got 4 columns instead of 11)
    Line #139 (got 14 columns instead of 11)
    Line #140 (got 1 columns instead of 11)
    Line #141 (got 8 columns instead of 11)
    Line #144 (got 4 columns instead of 11)
    Line #146 (got 10 columns instead of 11)
    Line #147 (got 8 columns instead of 11)
    Line #149 (got 9 columns instead of 11)
    Line #150 (got 3 columns instead of 11)
    Line #153 (got 7 columns instead of 11)
    Line #155 (got 6 columns instead of 11)
    Line #156 (got 5 columns instead of 11)
    Line #158 (got 9 columns instead of 11)
    Line #159 (got 6 columns instead of 11)
    Line #161 (got 13 columns instead of 11)
    Line #162 (got 13 columns instead of 11)
    Line #164 (got 7 columns instead of 11)
    Line #165 (got 3 columns instead of 11)
    Line #167 (got 9 columns instead of 11)
    Line #168 (got 10 columns instead of 11)
    Line #170 (got 9 columns instead of 11)
    Line #171 (got 12 columns instead of 11)
    Line #174 (got 8 columns instead of 11)
    Line #176 (got 5 columns instead of 11)
    Line #177 (got 7 columns instead of 11)
    Line #179 (got 7 columns instead of 11)
    Line #180 (got 7 columns instead of 11)
    Line #183 (got 5 columns instead of 11)
    Line #185 (got 14 columns instead of 11)
    Line #186 (got 3 columns instead of 11)
    Line #188 (got 8 columns instead of 11)
    Line #189 (got 3 columns instead of 11)
    Line #192 (got 3 columns instead of 11)
    Line #194 (got 6 columns instead of 11)
    Line #195 (got 4 columns instead of 11)
    Line #197 (got 14 columns instead of 11)
    Line #198 (got 2 columns instead of 11)
    Line #200 (got 10 columns instead of 11)
    Line #201 (got 4 columns instead of 11)
    Line #203 (got 7 columns instead of 11)
    Line #204 (got 3 columns instead of 11)
    Line #207 (got 7 columns instead of 11)
    Line #210 (got 4 columns instead of 11)
    Line #212 (got 13 columns instead of 11)
    Line #213 (got 8 columns instead of 11)
    Line #215 (got 6 columns instead of 11)
    Line #216 (got 9 columns instead of 11)
    Line #218 (got 9 columns instead of 11)
    Line #219 (got 4 columns instead of 11)
    Line #221 (got 9 columns instead of 11)
    Line #222 (got 3 columns instead of 11)
    Line #224 (got 8 columns instead of 11)
    Line #225 (got 8 columns instead of 11)
    Line #227 (got 8 columns instead of 11)
    Line #228 (got 7 columns instead of 11)
    Line #230 (got 16 columns instead of 11)
    Line #231 (got 2 columns instead of 11)
    Line #232 (got 3 columns instead of 11)
    Line #234 (got 10 columns instead of 11)
    Line #235 (got 8 columns instead of 11)
    Line #237 (got 14 columns instead of 11)
    Line #238 (got 4 columns instead of 11)
    Line #239 (got 5 columns instead of 11)
    Line #241 (got 10 columns instead of 11)
    Line #242 (got 2 columns instead of 11)
    Line #244 (got 8 columns instead of 11)
    Line #245 (got 7 columns instead of 11)
    Line #247 (got 12 columns instead of 11)
    Line #248 (got 2 columns instead of 11)
    Line #250 (got 13 columns instead of 11)
    Line #251 (got 4 columns instead of 11)
    Line #253 (got 10 columns instead of 11)
    Line #254 (got 6 columns instead of 11)
    Line #256 (got 5 columns instead of 11)
    Line #257 (got 3 columns instead of 11)
    Line #259 (got 14 columns instead of 11)
    Line #260 (got 8 columns instead of 11)
    Line #261 (got 2 columns instead of 11)
    Line #264 (got 7 columns instead of 11)
    Line #266 (got 12 columns instead of 11)
    Line #267 (got 8 columns instead of 11)
    Line #269 (got 14 columns instead of 11)
    Line #270 (got 9 columns instead of 11)
    Line #272 (got 6 columns instead of 11)
    Line #273 (got 3 columns instead of 11)
    Line #275 (got 8 columns instead of 11)
    Line #276 (got 3 columns instead of 11)
    Line #278 (got 15 columns instead of 11)
    Line #279 (got 12 columns instead of 11)
    Line #280 (got 4 columns instead of 11)
    Line #282 (got 9 columns instead of 11)
    Line #285 (got 9 columns instead of 11)
    Line #286 (got 5 columns instead of 11)
    Line #288 (got 10 columns instead of 11)
    Line #289 (got 2 columns instead of 11)
    Line #291 (got 13 columns instead of 11)
    Line #292 (got 3 columns instead of 11)
    Line #294 (got 8 columns instead of 11)
    Line #295 (got 7 columns instead of 11)
    Line #297 (got 9 columns instead of 11)
    Line #298 (got 4 columns instead of 11)
    Line #300 (got 7 columns instead of 11)
    Line #301 (got 2 columns instead of 11)
    Line #303 (got 10 columns instead of 11)
    Line #304 (got 9 columns instead of 11)
    Line #306 (got 8 columns instead of 11)
    Line #307 (got 2 columns instead of 11)
    Line #309 (got 13 columns instead of 11)
    Line #310 (got 5 columns instead of 11)
    Line #312 (got 9 columns instead of 11)
    Line #313 (got 2 columns instead of 11)
    Line #315 (got 9 columns instead of 11)
    Line #316 (got 3 columns instead of 11)
    Line #319 (got 4 columns instead of 11)
    Line #321 (got 9 columns instead of 11)
    Line #322 (got 4 columns instead of 11)
    Line #324 (got 14 columns instead of 11)
    Line #325 (got 2 columns instead of 11)
    Line #326 (got 4 columns instead of 11)
    Line #328 (got 10 columns instead of 11)
    Line #329 (got 3 columns instead of 11)
    Line #332 (got 3 columns instead of 11)
    Line #334 (got 10 columns instead of 11)
    Line #335 (got 2 columns instead of 11)
    Line #337 (got 13 columns instead of 11)
    Line #338 (got 3 columns instead of 11)
    Line #341 (got 5 columns instead of 11)
    Line #343 (got 15 columns instead of 11)
    Line #344 (got 4 columns instead of 11)
    Line #345 (got 4 columns instead of 11)
    Line #347 (got 6 columns instead of 11)
    Line #348 (got 3 columns instead of 11)
    Line #350 (got 7 columns instead of 11)
    Line #351 (got 3 columns instead of 11)
    Line #353 (got 10 columns instead of 11)
    Line #354 (got 2 columns instead of 11)
    Line #356 (got 10 columns instead of 11)
    Line #357 (got 3 columns instead of 11)
    Line #359 (got 10 columns instead of 11)
    Line #360 (got 4 columns instead of 11)
    Line #362 (got 9 columns instead of 11)
    Line #363 (got 4 columns instead of 11)
    Line #366 (got 6 columns instead of 11)
    Line #368 (got 7 columns instead of 11)
    Line #369 (got 6 columns instead of 11)
    Line #371 (got 12 columns instead of 11)
    Line #372 (got 3 columns instead of 11)
    Line #374 (got 6 columns instead of 11)
    Line #375 (got 7 columns instead of 11)
    Line #377 (got 13 columns instead of 11)
    Line #378 (got 5 columns instead of 11)
    Line #379 (got 5 columns instead of 11)
    Line #381 (got 9 columns instead of 11)
    Line #382 (got 3 columns instead of 11)
    Line #384 (got 10 columns instead of 11)
    Line #385 (got 5 columns instead of 11)
    Line #387 (got 7 columns instead of 11)
    Line #388 (got 6 columns instead of 11)
    Line #390 (got 6 columns instead of 11)
    Line #391 (got 5 columns instead of 11)
    Line #393 (got 8 columns instead of 11)
    Line #394 (got 3 columns instead of 11)
    Line #396 (got 6 columns instead of 11)
    Line #397 (got 7 columns instead of 11)
    Line #399 (got 12 columns instead of 11)
    Line #400 (got 10 columns instead of 11)
    Line #402 (got 8 columns instead of 11)
    Line #403 (got 3 columns instead of 11)
    Line #405 (got 12 columns instead of 11)
    Line #406 (got 4 columns instead of 11)
    Line #408 (got 9 columns instead of 11)
    Line #411 (got 15 columns instead of 11)
    Line #412 (got 4 columns instead of 11)
    Line #414 (got 9 columns instead of 11)
    Line #415 (got 5 columns instead of 11)
    Line #417 (got 16 columns instead of 11)
    Line #418 (got 7 columns instead of 11)
    Line #419 (got 10 columns instead of 11)
    Line #421 (got 7 columns instead of 11)
    Line #422 (got 7 columns instead of 11)
    Line #424 (got 9 columns instead of 11)
    Line #425 (got 7 columns instead of 11)
    Line #427 (got 9 columns instead of 11)
    Line #428 (got 7 columns instead of 11)
    Line #430 (got 9 columns instead of 11)
    Line #431 (got 10 columns instead of 11)
    Line #433 (got 8 columns instead of 11)
    Line #434 (got 3 columns instead of 11)
    Line #436 (got 8 columns instead of 11)
    Line #437 (got 2 columns instead of 11)
    Line #439 (got 9 columns instead of 11)
    Line #440 (got 7 columns instead of 11)
    Line #442 (got 13 columns instead of 11)
    Line #443 (got 4 columns instead of 11)
    Line #446 (got 5 columns instead of 11)
    Line #448 (got 10 columns instead of 11)
    Line #449 (got 5 columns instead of 11)
    Line #451 (got 13 columns instead of 11)
    Line #452 (got 1 columns instead of 11)
    Line #453 (got 6 columns instead of 11)
    Line #455 (got 9 columns instead of 11)
    Line #456 (got 7 columns instead of 11)
    Line #458 (got 9 columns instead of 11)
    Line #459 (got 6 columns instead of 11)
    Line #461 (got 10 columns instead of 11)
    Line #462 (got 4 columns instead of 11)
    Line #465 (got 2 columns instead of 11)
    Line #467 (got 15 columns instead of 11)
    Line #468 (got 1 columns instead of 11)
    Line #472 (got 3 columns instead of 11)
    Line #474 (got 9 columns instead of 11)
    Line #475 (got 8 columns instead of 11)
    Line #478 (got 7 columns instead of 11)
    Line #480 (got 12 columns instead of 11)
    Line #481 (got 4 columns instead of 11)
    Line #483 (got 7 columns instead of 11)
    Line #484 (got 3 columns instead of 11)
    Line #486 (got 12 columns instead of 11)
    Line #489 (got 8 columns instead of 11)
    Line #490 (got 4 columns instead of 11)
    Line #492 (got 8 columns instead of 11)
    Line #493 (got 7 columns instead of 11)
    Line #495 (got 7 columns instead of 11)
    Line #496 (got 10 columns instead of 11)
    Line #498 (got 7 columns instead of 11)
    Line #499 (got 8 columns instead of 11)
    Line #501 (got 8 columns instead of 11)
    Line #502 (got 8 columns instead of 11)
    Line #504 (got 8 columns instead of 11)
    Line #505 (got 4 columns instead of 11)
    Line #507 (got 7 columns instead of 11)
    Line #508 (got 3 columns instead of 11)
    Line #510 (got 9 columns instead of 11)
    Line #511 (got 2 columns instead of 11)
    Line #513 (got 10 columns instead of 11)
    Line #514 (got 3 columns instead of 11)
    Line #516 (got 8 columns instead of 11)
    Line #517 (got 3 columns instead of 11)
    Line #519 (got 7 columns instead of 11)
    Line #520 (got 2 columns instead of 11)
    Line #522 (got 9 columns instead of 11)
    Line #523 (got 5 columns instead of 11)
    Line #525 (got 7 columns instead of 11)
    Line #526 (got 7 columns instead of 11)
    Line #528 (got 8 columns instead of 11)
    Line #529 (got 3 columns instead of 11)
    Line #531 (got 7 columns instead of 11)
    Line #532 (got 4 columns instead of 11)
    Line #534 (got 10 columns instead of 11)
    Line #535 (got 7 columns instead of 11)
    Line #537 (got 9 columns instead of 11)
    Line #538 (got 3 columns instead of 11)
    Line #540 (got 5 columns instead of 11)
    Line #541 (got 3 columns instead of 11)
    Line #544 (got 3 columns instead of 11)
    Line #547 (got 5 columns instead of 11)
    Line #549 (got 14 columns instead of 11)
    Line #550 (got 5 columns instead of 11)
    Line #552 (got 8 columns instead of 11)
    Line #553 (got 3 columns instead of 11)
    Line #555 (got 6 columns instead of 11)
    Line #556 (got 5 columns instead of 11)
    Line #558 (got 8 columns instead of 11)
    Line #559 (got 10 columns instead of 11)
    Line #561 (got 10 columns instead of 11)
    Line #562 (got 2 columns instead of 11)
    Line #564 (got 10 columns instead of 11)
    Line #565 (got 9 columns instead of 11)
    Line #567 (got 13 columns instead of 11)
    Line #568 (got 7 columns instead of 11)
    Line #570 (got 13 columns instead of 11)
    Line #571 (got 7 columns instead of 11)
    Line #573 (got 12 columns instead of 11)
    Line #574 (got 4 columns instead of 11)
    Line #577 (got 3 columns instead of 11)
    Line #579 (got 9 columns instead of 11)
    Line #580 (got 8 columns instead of 11)
    Line #582 (got 8 columns instead of 11)
    Line #583 (got 7 columns instead of 11)
    Line #585 (got 10 columns instead of 11)
    Line #586 (got 6 columns instead of 11)
    Line #589 (got 6 columns instead of 11)
    Line #591 (got 15 columns instead of 11)
    Line #592 (got 6 columns instead of 11)
    Line #593 (got 2 columns instead of 11)
    Line #595 (got 7 columns instead of 11)
    Line #596 (got 3 columns instead of 11)
    Line #598 (got 7 columns instead of 11)
    Line #599 (got 10 columns instead of 11)
    Line #602 (got 5 columns instead of 11)
    Line #604 (got 9 columns instead of 11)
    Line #605 (got 3 columns instead of 11)
    Line #607 (got 10 columns instead of 11)
    Line #608 (got 7 columns instead of 11)
    Line #610 (got 12 columns instead of 11)
    Line #611 (got 7 columns instead of 11)
    Line #613 (got 8 columns instead of 11)
    Line #614 (got 12 columns instead of 11)
    Line #616 (got 6 columns instead of 11)
    Line #617 (got 2 columns instead of 11)
    Line #619 (got 7 columns instead of 11)
    Line #620 (got 7 columns instead of 11)
    Line #622 (got 12 columns instead of 11)
    Line #623 (got 8 columns instead of 11)
    Line #626 (got 7 columns instead of 11)
    Line #628 (got 8 columns instead of 11)
    Line #629 (got 10 columns instead of 11)
    Line #631 (got 7 columns instead of 11)
    Line #632 (got 2 columns instead of 11)
    Line #634 (got 6 columns instead of 11)
    Line #635 (got 2 columns instead of 11)
    Line #637 (got 9 columns instead of 11)
    Line #638 (got 5 columns instead of 11)
    Line #640 (got 7 columns instead of 11)
    Line #641 (got 12 columns instead of 11)
    Line #643 (got 8 columns instead of 11)
    Line #644 (got 12 columns instead of 11)
    Line #646 (got 10 columns instead of 11)
    Line #647 (got 7 columns instead of 11)
    Line #649 (got 5 columns instead of 11)
    Line #650 (got 7 columns instead of 11)
    Line #652 (got 9 columns instead of 11)
    Line #653 (got 3 columns instead of 11)
    Line #655 (got 6 columns instead of 11)
    Line #656 (got 8 columns instead of 11)
    Line #658 (got 6 columns instead of 11)
    Line #659 (got 3 columns instead of 11)
    Line #661 (got 8 columns instead of 11)
    Line #662 (got 4 columns instead of 11)
    Line #665 (got 2 columns instead of 11)
    Line #667 (got 10 columns instead of 11)
    Line #668 (got 3 columns instead of 11)
    Line #670 (got 7 columns instead of 11)
    Line #671 (got 3 columns instead of 11)
    Line #673 (got 7 columns instead of 11)
    Line #674 (got 8 columns instead of 11)
    Line #676 (got 6 columns instead of 11)
    Line #677 (got 5 columns instead of 11)
    Line #679 (got 10 columns instead of 11)
    Line #680 (got 3 columns instead of 11)
    Line #682 (got 8 columns instead of 11)
    Line #683 (got 3 columns instead of 11)
    Line #686 (got 3 columns instead of 11)
    Line #688 (got 7 columns instead of 11)
    Line #689 (got 5 columns instead of 11)
    Line #692 (got 2 columns instead of 11)
    Line #694 (got 8 columns instead of 11)
    Line #695 (got 6 columns instead of 11)
    Line #697 (got 14 columns instead of 11)
    Line #698 (got 6 columns instead of 11)
    Line #700 (got 10 columns instead of 11)
    Line #701 (got 4 columns instead of 11)
    Line #703 (got 6 columns instead of 11)
    Line #704 (got 9 columns instead of 11)
    Line #706 (got 16 columns instead of 11)
    Line #707 (got 9 columns instead of 11)
    Line #708 (got 2 columns instead of 11)
    Line #711 (got 2 columns instead of 11)
    Line #714 (got 6 columns instead of 11)
    Line #716 (got 10 columns instead of 11)
    Line #717 (got 2 columns instead of 11)
    Line #720 (got 6 columns instead of 11)
    Line #722 (got 8 columns instead of 11)
    Line #723 (got 7 columns instead of 11)
    Line #725 (got 6 columns instead of 11)
    Line #726 (got 4 columns instead of 11)
    Line #728 (got 7 columns instead of 11)
    Line #729 (got 8 columns instead of 11)
    Line #731 (got 7 columns instead of 11)
    Line #732 (got 8 columns instead of 11)
    Line #734 (got 7 columns instead of 11)
    Line #735 (got 12 columns instead of 11)
    Line #737 (got 7 columns instead of 11)
    Line #738 (got 6 columns instead of 11)
    Line #740 (got 9 columns instead of 11)
    Line #741 (got 8 columns instead of 11)
    Line #743 (got 8 columns instead of 11)
    Line #744 (got 2 columns instead of 11)
    Line #746 (got 9 columns instead of 11)
    Line #747 (got 6 columns instead of 11)
    Line #749 (got 10 columns instead of 11)
    Line #750 (got 2 columns instead of 11)
    Line #752 (got 5 columns instead of 11)
    Line #755 (got 7 columns instead of 11)
    Line #756 (got 4 columns instead of 11)
    Line #758 (got 12 columns instead of 11)
    Line #759 (got 2 columns instead of 11)
    Line #761 (got 12 columns instead of 11)
    Line #762 (got 4 columns instead of 11)
    Line #764 (got 7 columns instead of 11)
    Line #765 (got 4 columns instead of 11)
    Line #767 (got 7 columns instead of 11)
    Line #768 (got 3 columns instead of 11)
    Line #770 (got 7 columns instead of 11)
    Line #771 (got 4 columns instead of 11)
    Line #773 (got 7 columns instead of 11)
    Line #774 (got 4 columns instead of 11)
    Line #776 (got 5 columns instead of 11)
    Line #777 (got 5 columns instead of 11)
    Line #779 (got 9 columns instead of 11)
    Line #780 (got 6 columns instead of 11)
    Line #782 (got 6 columns instead of 11)
    Line #783 (got 4 columns instead of 11)
    Line #786 (got 7 columns instead of 11)
    Line #788 (got 8 columns instead of 11)
    Line #789 (got 4 columns instead of 11)
    Line #792 (got 5 columns instead of 11)
    Line #794 (got 12 columns instead of 11)
    Line #795 (got 3 columns instead of 11)
    Line #797 (got 7 columns instead of 11)
    Line #798 (got 3 columns instead of 11)
    Line #800 (got 13 columns instead of 11)
    Line #801 (got 4 columns instead of 11)
    Line #802 (got 3 columns instead of 11)
    Line #804 (got 13 columns instead of 11)
    Line #805 (got 3 columns instead of 11)
    Line #807 (got 7 columns instead of 11)
    Line #808 (got 3 columns instead of 11)
    Line #810 (got 8 columns instead of 11)
    Line #811 (got 9 columns instead of 11)
    Line #813 (got 13 columns instead of 11)
    Line #814 (got 13 columns instead of 11)
    Line #816 (got 7 columns instead of 11)
    Line #817 (got 6 columns instead of 11)
    Line #819 (got 12 columns instead of 11)
    Line #820 (got 1 columns instead of 11)
    Line #823 (got 13 columns instead of 11)
    Line #824 (got 8 columns instead of 11)
    Line #826 (got 14 columns instead of 11)
    Line #827 (got 2 columns instead of 11)
    Line #828 (got 3 columns instead of 11)
    Line #830 (got 10 columns instead of 11)
    Line #831 (got 6 columns instead of 11)
    Line #833 (got 7 columns instead of 11)
    Line #834 (got 6 columns instead of 11)
    Line #836 (got 8 columns instead of 11)
    Line #837 (got 5 columns instead of 11)
    Line #839 (got 8 columns instead of 11)
    Line #840 (got 4 columns instead of 11)
    Line #842 (got 12 columns instead of 11)
    Line #843 (got 4 columns instead of 11)
    Line #845 (got 10 columns instead of 11)
    Line #846 (got 9 columns instead of 11)
    Line #849 (got 8 columns instead of 11)
    Line #851 (got 9 columns instead of 11)
    Line #852 (got 3 columns instead of 11)
    Line #855 (got 6 columns instead of 11)
    Line #857 (got 12 columns instead of 11)
    Line #858 (got 5 columns instead of 11)
    Line #860 (got 8 columns instead of 11)
    Line #861 (got 7 columns instead of 11)

In [ ]:
data.shape

In [ ]:
aa.itemsize

In [ ]:
aa.nbytes

In [ ]:
aa.ndim

In [ ]:
#indexing
aa[0]

In [ ]:
aa[1]

In [ ]:
aa[-1]

In [ ]:
np.dot(aa,aa)

In [ ]:
np.mean(aa[:3])

In [ ]:
np.mean(aa[:3]).min

In [ ]:
a=np.arange(25).reshape(5,5)
a

In [ ]:
a

In [ ]:
a,b=a.shape
B=np.reshape((a,1))
B

In [ ]:
stuff = ['hello', 'hi', 'how are you doing', 'im fine', 'how about you']
for a in stuff:
     stuff.remove(a)
stuff

In [1]:
import numpy as np
a=np.random.random((2,3))
a

array([[ 0.06491888,  0.57929261,  0.36270323],
       [ 0.05910944,  0.67494475,  0.72219228]])

In [2]:
a.sum()

2.4631611908837323

In [3]:
a.sum(axis=0)

array([ 0.12402831,  1.25423736,  1.08489552])

In [4]:
a.cumsum()

array([ 0.06491888,  0.64421148,  1.00691472,  1.06602415,  1.74096891,
        2.46316119])

In [5]:
a.cumsum(axis=1)

array([[ 0.06491888,  0.64421148,  1.00691472],
       [ 0.05910944,  0.73405419,  1.45624647]])

In [6]:
a.min()

0.059109436900967482

In [7]:
a.max()

0.72219228479273179

In [8]:
a.max(axis=0)

array([ 0.06491888,  0.67494475,  0.72219228])

In [24]:
import pandas as pf
df1=pf.read_csv('/Users/vishwaprabhakarsingh/anaconda/pkgs/pandas-0.22.0-py27h0a44026_0/lib/python2.7/site-packages/pandas/tests/data/iris.csv')
df1.head(10)

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa
6          4.6         3.4          1.4         0.3  Iris-setosa
7          5.0         3.4          1.5         0.2  Iris-setosa
8          4.4         2.9          1.4         0.2  Iris-setosa
9          4.9         3.1          1.5         0.1  Iris-setosa

In [28]:
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
df=sns.load_dataset('/Users/vishwaprabhakarsingh/anaconda/pkgs/pandas-0.22.0-py27h0a44026_0/lib/python2.7/site-packages/pandas/tests/data/iris.csv')
sns.countplot(y='SepalLength',data=df)

HTTPError: HTTP Error 404: Not Found